// Generated by gencpp from file eurobot/pathData.msg
// DO NOT EDIT!


#ifndef EUROBOT_MESSAGE_PATHDATA_H
#define EUROBOT_MESSAGE_PATHDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eurobot
{
template <class ContainerAllocator>
struct pathData_
{
  typedef pathData_<ContainerAllocator> Type;

  pathData_()
    : function()
    , value(0)  {
    }
  pathData_(const ContainerAllocator& _alloc)
    : function(_alloc)
    , value(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _function_type;
  _function_type function;

   typedef int16_t _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::eurobot::pathData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eurobot::pathData_<ContainerAllocator> const> ConstPtr;

}; // struct pathData_

typedef ::eurobot::pathData_<std::allocator<void> > pathData;

typedef boost::shared_ptr< ::eurobot::pathData > pathDataPtr;
typedef boost::shared_ptr< ::eurobot::pathData const> pathDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eurobot::pathData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eurobot::pathData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace eurobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'eurobot': ['/home/ubuntu/eurobot_ws/src/eurobot/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::eurobot::pathData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eurobot::pathData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eurobot::pathData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eurobot::pathData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eurobot::pathData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eurobot::pathData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eurobot::pathData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58f2eabdeb5bb2cf5da92ef285242afb";
  }

  static const char* value(const ::eurobot::pathData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58f2eabdeb5bb2cfULL;
  static const uint64_t static_value2 = 0x5da92ef285242afbULL;
};

template<class ContainerAllocator>
struct DataType< ::eurobot::pathData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eurobot/pathData";
  }

  static const char* value(const ::eurobot::pathData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eurobot::pathData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string function # for example turnLeft\n\
int16 value # 20 deg\n\
";
  }

  static const char* value(const ::eurobot::pathData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eurobot::pathData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.function);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct pathData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eurobot::pathData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eurobot::pathData_<ContainerAllocator>& v)
  {
    s << indent << "function: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.function);
    s << indent << "value: ";
    Printer<int16_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUROBOT_MESSAGE_PATHDATA_H
